//url写入state
export const INSERT_URL = 'INSERT_URL';
//当前页
export const PAGE_ACTIVE = 'PAGE_ACTIVE';

//学生列表
export const STUDENT_REQUEST = 'STUDENT_REQUEST';
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS';
export const STUDENT_FAILURE = 'STUDENT_FAILURE';
//学生搜索列表
export const STUDENT_SEARCH_REQUEST = 'STUDENT_SEARCH_REQUEST';
export const STUDENT_SEARCH_SUCCESS = 'STUDENT_SEARCH_SUCCESS';
export const STUDENT_SEARCH_FAILURE = 'STUDENT_SEARCH_FAILURE';
//学生信息
export const STUDENTINFO_REQUEST = 'STUDENTINFO_REQUEST';
export const STUDENTINFO_SUCCESS = 'STUDENTINFO_SUCCESS';
export const STUDENTINFO_FAILURE = 'STUDENTINFO_FAILURE';

//学生里程
export const MILEAGE_REQUEST = 'MILEAGE_REQUEST';
export const MILEAGE_SUCCESS = 'MILEAGE_SUCCESS';
export const MILEAGE_FAILURE = 'MILEAGE_FAILURE';

//学生活动
export const STUDENT_ACTIVITY_REQUEST = 'STUDENT_ACTIVITY_REQUEST';
export const STUDENT_ACTIVITY_SUCCESS = 'STUDENT_ACTIVITY_SUCCESS';
export const STUDENT_ACTIVITY_FAILURE = 'STUDENT_ACTIVITY_FAILURE';

//学分规则
export const GETRULE_REQUEST = 'GETRULE_REQUEST';
export const GETRULE_SUCCESS = 'GETRULE_SUCCESS';
export const GETRULE_FAILURE = 'GETRULE_FAILURE';


//管理员列表
export const ADMIN_REQUEST = 'ADMIN_REQUEST';
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';
export const ADMIN_FAILURE = 'ADMIN_FAILURE';

//获取管理员信息
export const GETADMIN_REQUEST = 'GETADMIN_REQUEST';
export const GETADMIN_SUCCESS = 'GETADMIN_SUCCESS';
export const GETADMIN_FAILURE = 'GETADMIN_FAILURE';

//发布
export const RELEASE_REQUEST = 'RELEASE_REQUEST';
export const RELEASE_SUCCESS = 'RELEASE_SUCCESS';
export const RELEASE_FAILURE = 'RELEASE_FAILURE';

//编辑
export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_FAILURE = 'EDIT_FAILURE';

//删除
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

//重置密码
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';

//设置俱乐部列表
export const SETCLUBLIST_REQUEST = 'SETCLUBLIST_REQUEST';
export const SETCLUBLIST_SUCCESS = 'SETCLUBLIST_SUCCESS';
export const SETCLUBLIST_FAILURE = 'SETCLUBLIST_FAILURE';

//俱乐部列表
export const CLUBLIST_REQUEST = 'CLUBLIST_REQUEST';
export const CLUBLIST_SUCCESS = 'CLUBLIST_SUCCESS';
export const CLUBLIST_FAILURE = 'CLUBLIST_FAILURE';

//俱乐部搜索列表
export const CLUBSEARCH_REQUEST = 'CLUBSEARCH_REQUEST';
export const CLUBSEARCH_SUCCESS = 'CLUBSEARCH_SUCCESS';
export const CLUBSEARCH_FAILURE = 'CLUBSEARCH_FAILURE';

//俱乐部信息
export const CLUBINFO_REQUEST = 'CLUBINFO_REQUEST';
export const CLUBINFO_SUCCESS = 'CLUBINFO_SUCCESS';
export const CLUBINFO_FAILURE = 'CLUBINFO_FAILURE';

//俱乐部成员列表
export const CLUBMEMBERLIST_REQUEST = 'CLUBMEMBERLIST_REQUEST';
export const CLUBMEMBERLIST_SUCCESS = 'CLUBMEMBERLIST_SUCCESS';
export const CLUBMEMBERLIST_FAILURE = 'CLUBMEMBERLIST_FAILURE';

//俱乐部活动列表
export const CLUBACTIVITYLIST_REQUEST = 'CLUBACTIVITYLIST_REQUEST';
export const CLUBACTIVITYLIST_SUCCESS = 'CLUBACTIVITYLIST_SUCCESS';
export const CLUBACTIVITYLIST_FAILURE = 'CLUBACTIVITYLIST_FAILURE';

//活动列表
export const ACTIVITY_REQUEST = 'ACTIVITY_REQUEST';
export const ACTIVITY_SUCCESS = 'ACTIVITY_SUCCESS';
export const ACTIVITY_FAILURE = 'ACTIVITY_FAILURE';


//活动详情
export const ACTIVITYDETAILS_REQUEST = 'ACTIVITYDETAILS_REQUEST';
export const ACTIVITYDETAILS_SUCCESS = 'ACTIVITYDETAILS_SUCCESS';
export const ACTIVITYDETAILS_FAILURE = 'ACTIVITYDETAILS_FAILURE';

//活动成员
export const ACTIVITYMEMBER_REQUEST = 'ACTIVITYMEMBER_REQUEST';
export const ACTIVITYMEMBER_SUCCESS = 'ACTIVITYMEMBER_SUCCESS';
export const ACTIVITYMEMBER_FAILURE = 'ACTIVITYMEMBER_FAILURE';


//获取学生等级
export const USETGRADE_REQUEST = 'USETGRADE_REQUEST';
export const USETGRADE_SUCCESS = 'USETGRADE_SUCCESS';
export const USETGRADE_FAILURE = 'USETGRADE_FAILURE';
//设置学生等级
export const USETGRADEEDIT_REQUEST = 'USETGRADEEDIT_REQUEST';
export const USETGRADEEDIT_SUCCESS = 'USETGRADEEDIT_SUCCESS';
export const USETGRADEEDIT_FAILURE = 'USETGRADEEDIT_FAILURE';

//获取基本设置
export const GETSETRULE_REQUEST = 'GETSETRULE_REQUEST';
export const GETSETRULE_SUCCESS = 'GETSETRULE_SUCCESS';
export const GETSETRULE_FAILURE = 'GETSETRULE_FAILURE';

//修改基本设置
export const EDITSETRULE_REQUEST = 'EDITSETRULE_REQUEST';
export const EDITSETRULE_SUCCESS = 'EDITSETRULE_SUCCESS';
export const EDITSETRULE_FAILURE = 'EDITSETRULE_FAILURE';

//修改基本设置
export const ACTIVITYSEARCH_REQUEST = 'ACTIVITYSEARCH_REQUEST';
export const ACTIVITYSEARCH_SUCCESS = 'ACTIVITYSEARCH_SUCCESS';
export const ACTIVITYSEARCH_FAILURE = 'ACTIVITYSEARCH_FAILURE';


//登录
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

//修改密码
export const EDITPASS_REQUEST = 'EDITPASS_REQUEST';
export const EDITPASS_SUCCESS = 'EDITPASS_SUCCESS';
export const EDITPASS_FAILURE = 'EDITPASS_FAILURE';

//退出
export const SIGNOUT_SESSION = 'SIGNOUT_SESSION';